CREATE TABLE `testingplus`.`user` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC));
